spring.application.name=ContentPublishing
spring.datasource.url=jdbc:h2:mem:content_publishing;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=salah
spring.datasource.password=atypon2026
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8081
spring.cache.type=simple
