spring.application.name=ContentPublishing
spring.datasource.url=jdbc:mysql://localhost:3307/mydb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=8080
spring.cache.type=simple
app.pagination.default-size=10
app.pagination.max-size=50
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000